[package]
name = "rust_base"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stderrlog = "0.6.0"
log = "0.4.20"
backtrace = "0.3.69"